WIDTH, HEIGHT = 960, 640
TILE_SIZE = 64
TILES_X = WIDTH / TILE_SIZE
TILES_Y = HEIGHT / TILE_SIZE

Z_MAP, Z_SHADOWS, Z_HINTS, Z_OBJECTS, Z_ACTORS = *0...1337

DIR_UP, DIR_UP_RIGHT, DIR_RIGHT, DIR_DOWN_RIGHT,
  DIR_DOWN, DIR_DOWN_LEFT, DIR_LEFT, DIR_UP_LEFT = *0...8

FOUR_DIRECTIONS = 0, 2, 4, 6
EIGHT_DIRECTIONS = *0...8

FONT_NAME = 'Georgia'
